/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    FormInputBasic: typeof import('./src/components/inputs/FormInputBasic.vue')['default']
    FormInputContainer: typeof import('./src/components/inputs/FormInputContainer.vue')['default']
    FormInputGeneral: typeof import('./src/components/inputs/FormInputGeneral.vue')['default']
    FormInputLabel: typeof import('./src/components/inputs/FormInputLabel.vue')['default']
    FormInputSelect: typeof import('./src/components/inputs/FormInputSelect.vue')['default']
    FormInputTextarea: typeof import('./src/components/inputs/FormInputTextarea.vue')['default']
    FormInputTreeSelect: typeof import('./src/components/inputs/FormInputTreeSelect.vue')['default']
    PaperCard: typeof import('./src/components/PaperSelector/PaperCard.vue')['default']
    PaperSelectorContainer: typeof import('./src/components/PaperSelector/PaperSelectorContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/atoms/SvgIcon.vue')['default']
  }
}
