/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COLOR_MAP: typeof import('./mock/paperData').COLOR_MAP
  const EffectScope: typeof import('vue').EffectScope
  const PaperModel: typeof import('./schema/paper/model').PaperModel
  const RAW_PAPERS_DATA: typeof import('./mock/paperData').RAW_PAPERS_DATA
  const VALIDATORS: typeof import('./config/validators').VALIDATORS
  const _: typeof import('lodash').default
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineField: typeof import('./schema/field/index').defineField
  const defineInput: typeof import('./schema/input/index').defineInput
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const extractFilteredOptions: typeof import('./mock/paperData').extractFilteredOptions
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getOptionsOf: typeof import('./mock/paperData').getOptionsOf
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isValidAddress: typeof import('./config/validators').isValidAddress
  const isValidArray: typeof import('./config/validators').isValidArray
  const isValidBool: typeof import('./config/validators').isValidBool
  const isValidCellphone: typeof import('./config/validators').isValidCellphone
  const isValidCitizenId: typeof import('./config/validators').isValidCitizenId
  const isValidDate: typeof import('./config/validators').isValidDate
  const isValidDateRange: typeof import('./config/validators').isValidDateRange
  const isValidDateTime: typeof import('./config/validators').isValidDateTime
  const isValidEmail: typeof import('./config/validators').isValidEmail
  const isValidFile: typeof import('./config/validators').isValidFile
  const isValidNonNegativeNumber: typeof import('./config/validators').isValidNonNegativeNumber
  const isValidNone: typeof import('./config/validators').isValidNone
  const isValidNoneAndNumber: typeof import('./config/validators').isValidNoneAndNumber
  const isValidNumberRange: typeof import('./config/validators').isValidNumberRange
  const isValidPosIntOrZero: typeof import('./config/validators').isValidPosIntOrZero
  const isValidPositiveNumber: typeof import('./config/validators').isValidPositiveNumber
  const isValidString: typeof import('./config/validators').isValidString
  const isValidStringLengthBetween4And6: typeof import('./config/validators').isValidStringLengthBetween4And6
  const isValidStringLengthBetween4And8: typeof import('./config/validators').isValidStringLengthBetween4And8
  const isValidTelephone: typeof import('./config/validators').isValidTelephone
  const isValidVATId: typeof import('./config/validators').isValidVATId
  const ld: typeof import('lodash').default
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const mdiC: typeof import('./config/icons').mdiC
  const mdiCheck: typeof import('./config/icons').mdiCheck
  const mdiChevronDown: typeof import('./config/icons').mdiChevronDown
  const mdiCloseCircle: typeof import('./config/icons').mdiCloseCircle
  const mdiCloseThick: typeof import('./config/icons').mdiCloseThick
  const mdiMagnify: typeof import('./config/icons').mdiMagnify
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFieldStore: typeof import('./schema/field/store').useFieldStore
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const validators: typeof import('./config/validators').default
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const wrapValidator: typeof import('./config/validators').wrapValidator
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FieldFunctionality, FieldRequired, FieldOptions, GeneralFieldConfig, NumberFieldConfig, SelectFieldConfig, FieldConfig } from './schema/field/types'
  import('./schema/field/types')
  // @ts-ignore
  export type { InputLayout, InputConfig } from './schema/input/types'
  import('./schema/input/types')
  // @ts-ignore
  export type { Paper, PaperWithColor } from './schema/paper/types'
  import('./schema/paper/types')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly COLOR_MAP: UnwrapRef<typeof import('./mock/paperData')['COLOR_MAP']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly RAW_PAPERS_DATA: UnwrapRef<typeof import('./mock/paperData')['RAW_PAPERS_DATA']>
    readonly VALIDATORS: UnwrapRef<typeof import('./config/validators')['VALIDATORS']>
    readonly _: UnwrapRef<typeof import('lodash')['default']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineField: UnwrapRef<typeof import('./schema/field/index')['defineField']>
    readonly defineInput: UnwrapRef<typeof import('./schema/input/index')['defineInput']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extractFilteredOptions: UnwrapRef<typeof import('./mock/paperData')['extractFilteredOptions']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getOptionsOf: UnwrapRef<typeof import('./mock/paperData')['getOptionsOf']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isValidAddress: UnwrapRef<typeof import('./config/validators')['isValidAddress']>
    readonly isValidArray: UnwrapRef<typeof import('./config/validators')['isValidArray']>
    readonly isValidBool: UnwrapRef<typeof import('./config/validators')['isValidBool']>
    readonly isValidCellphone: UnwrapRef<typeof import('./config/validators')['isValidCellphone']>
    readonly isValidCitizenId: UnwrapRef<typeof import('./config/validators')['isValidCitizenId']>
    readonly isValidDate: UnwrapRef<typeof import('./config/validators')['isValidDate']>
    readonly isValidDateRange: UnwrapRef<typeof import('./config/validators')['isValidDateRange']>
    readonly isValidDateTime: UnwrapRef<typeof import('./config/validators')['isValidDateTime']>
    readonly isValidEmail: UnwrapRef<typeof import('./config/validators')['isValidEmail']>
    readonly isValidFile: UnwrapRef<typeof import('./config/validators')['isValidFile']>
    readonly isValidNonNegativeNumber: UnwrapRef<typeof import('./config/validators')['isValidNonNegativeNumber']>
    readonly isValidNone: UnwrapRef<typeof import('./config/validators')['isValidNone']>
    readonly isValidNoneAndNumber: UnwrapRef<typeof import('./config/validators')['isValidNoneAndNumber']>
    readonly isValidNumberRange: UnwrapRef<typeof import('./config/validators')['isValidNumberRange']>
    readonly isValidPosIntOrZero: UnwrapRef<typeof import('./config/validators')['isValidPosIntOrZero']>
    readonly isValidPositiveNumber: UnwrapRef<typeof import('./config/validators')['isValidPositiveNumber']>
    readonly isValidString: UnwrapRef<typeof import('./config/validators')['isValidString']>
    readonly isValidStringLengthBetween4And6: UnwrapRef<typeof import('./config/validators')['isValidStringLengthBetween4And6']>
    readonly isValidStringLengthBetween4And8: UnwrapRef<typeof import('./config/validators')['isValidStringLengthBetween4And8']>
    readonly isValidTelephone: UnwrapRef<typeof import('./config/validators')['isValidTelephone']>
    readonly isValidVATId: UnwrapRef<typeof import('./config/validators')['isValidVATId']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly mdiCheck: UnwrapRef<typeof import('./config/icons')['mdiCheck']>
    readonly mdiChevronDown: UnwrapRef<typeof import('./config/icons')['mdiChevronDown']>
    readonly mdiCloseCircle: UnwrapRef<typeof import('./config/icons')['mdiCloseCircle']>
    readonly mdiCloseThick: UnwrapRef<typeof import('./config/icons')['mdiCloseThick']>
    readonly mdiMagnify: UnwrapRef<typeof import('./config/icons')['mdiMagnify']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useFieldStore: UnwrapRef<typeof import('./schema/field/store')['useFieldStore']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly wrapValidator: UnwrapRef<typeof import('./config/validators')['wrapValidator']>
  }
}